Added file and version change detection

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,6 +15,54 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4 # Use the checkout action to get your code
+        with:
+          fetch-depth: 2
+
+      - name: Detect file changes
+        id: fileChanges
+        run: |
+          echo "checking files"
+
+          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
+          echo "Changed Files..."
+          echo "$CHANGED_FILES"
+          
+          if [ -z "$CHANGED_FILES" ]; then
+            echo "No changes detected."
+            exit 1
+          fi
+
+          CHANGED_IN_FOLDERS=$(git diff --name-only HEAD~1 HEAD -- src public)
+
+          if [ -n "$CHANGED_IN_FOLDERS" ]; then
+            echo "Changes in src or public"
+          else
+            echo "No changes in src or public"
+          fi
+
+          if ! echo "$CHANGED_FILES" | grep -q "package.json$"; then
+            echo "Package version not modified."
+            exit 1
+          fi
+
+          OLD_VERSION=$(git show HEAD~1:package.json | jq -r '.version')
+          NEW_VERSION=$(jq -r '.version' package.json)
+
+          echo "Old version: $OLD_VERSION"
+          echo "New version: $NEW_VERSION"
+
+          if [ "$OLD_VERSION" = "$NEW_VERSION" ]; then
+            echo "package.json version was not bumped."
+            exit 1
+          fi
+
+          if dpkg --compare-versions "$NEW_VERSION" lt "$OLD_VERSION"; then
+            echo "package.json version can't be downgraded"
+            exit 1
+          fi
+
+          echo "package.json version bumped."
+
       
       - name: Set up Node.js
         uses: actions/setup-node@v4 # Use the setup-node action to configure Node.js
